apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: raincatcher-server
      name: raincatcher-server
    name: raincatcher-server
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: raincatcher-server
      name: raincatcher-server
    name: raincatcher-server
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: raincatcher-server:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/feedhenry-raincatcher/raincatcher-server.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:6
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: dMRcuYXdb4j9OapPXR-l
      type: GitHub
    - generic:
        secret: nm26q1wD3XF-ACXYaLtc
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: raincatcher-server
      name: raincatcher-server
    name: raincatcher-server
  spec:
    replicas: 1
    selector:
      app: raincatcher-server
      deploymentconfig: raincatcher-server
      name: raincatcher-server
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: raincatcher-server
          deploymentconfig: raincatcher-server
          name: raincatcher-server
      spec:
        containers:
        - image: raincatcher-server:latest
          name: raincatcher-server
          ports:
          - containerPort: 8001
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - raincatcher-server
        from:
          kind: ImageStreamTag
          name: raincatcher-server:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: raincatcher-server
      name: raincatcher-server
    name: raincatcher-server
  spec:
    ports:
    - name: 8001-tcp
      port: 8001
      protocol: TCP
      targetPort: 8001
    selector:
      app: raincatcher-server
      deploymentconfig: raincatcher-server
      name: raincatcher-server
  status:
    loadBalancer: {}
kind: List
metadata: {}
